


const produceData = [

    {   name: 'banana',
        price: .50,
        total: 0},
    {   name: 'zucchini', 
        price: 2.99,
        total: 0},
    {   name: 'redBellPepper', 
        price: 2.69,
        total: 0},
    {   name: 'broccoli', 
        price: 2.99,
        total: 0},
    {   name: 'blueBerries', 
        price: 4.49,
        total: 0},
    {   name: 'lime', 
        price: .50,
        total: 0},
    {   name: 'strawberries', 
        price: 3.59,
        total: 0},
    {   name: 'tomatoes', 
        price: 2.24,
        total: 0},
    {   name: 'onion', 
        price: 1.69,
        total: 0},
    {   name: 'avacodo', 
        price: 1.49,
        total: 0},
    {   name: 'fennel', 
        price: 2.49,
        total: 0},
    {   name: 'mango', 
        price: 1.99,
        total: 0},
    {   name: 'corn', 
        price: 1.99,
        total: 0},
    {   name: 'apple', 
        price: 1.52,
        total: 0},
    {   name: 'lemon', 
        price: .89,
        total: 0},
    {   name: 'asparagus', 
        price: 3.49,
        total: 0},
    {   name: 'ginger', 
        price: 3.99,
        total: 0},
    {   name: 'garlic', 
        price: 3.99,
        total: 0},
    {   name: 'potato', 
        price: .99,
        total: 0},
    {   name: 'kiwi', 
        price: .99,
        total: 0}
];

export default produceData;